shop/routes/admin_routes.py
import os
import secrets
from PIL import Image
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import current_user, login_user, login_required, logout_user
from shop.forms import AdminRegisterForm, AdminLoginForm, AdminAddProductForm, AdminUpdateProductForm 
from shop.models import Product, Admin
from shop import app, db, bcrypt

admin_blueprint = Blueprint("admin_blueprint", __name__)

@admin_blueprint.get("/admin/dashboard")
@login_required
def admin_dashboard():
  products = Product.query.all()
  return render_template("admin_dashboard.html", title="Admin Dashboard", products=products)


@admin_blueprint.route("/admin/register", methods=["GET", "POST"])
def admin_register():
  if current_user.is_authenticated:
    return redirect(url_for("admin_blueprint.admin_dashboard"))
  admins = Admin.query.all()
  if admins:
    return redirect(url_for("admin_blueprint.admin_login"))
  form = AdminRegisterForm()
  if form.validate_on_submit():
    hashed_password = bcrypt.generate_password_hash(form.password.data).decode()
    new_admin = Admin(name=form.name.data, password=hashed_password)
    db.session.add(new_admin)
    db.session.commit()
    flash(f'Admin Account successfully created for {form.name.data}', 'success')
    return redirect(url_for("admin_blueprint.admin_login"))
  return render_template("admin_register.html", title="Admin Register", form=form)


@admin_blueprint.route("/admin/login", methods=["GET", "POST"])
def admin_login():
  if current_user.is_authenticated:
    return redirect(url_for("admin_blueprint.admin_dashboard"))
  admins = Admin.query.all()
  form = AdminLoginForm()
  if form.validate_on_submit():
    admin = Admin.query.filter_by(name=form.name.data).first()
    if admin and bcrypt.check_password_hash(admin.password.encode("utf-8"), form.password.data):
      login_user(admin)
      flash(f"You are now logged in as {admin.name}", "success")
      return redirect(url_for("admin_blueprint.admin_dashboard"))
    else:
      flash("Login unsuccessful, please check username or password", "danger")
      return redirect(url_for('admin_blueprint.admin_login'))
  return render_template("admin_login.html", title="Admin Login", form=form, admins=admins) 


@admin_blueprint.route("/admin/product/new", methods=["GET", "POST"])
@login_required
def admin_addproduct():
  form = AdminAddProductForm()
  if form.validate_on_submit():
    random_hex = secrets.token_hex(8)
    _, file_extension = os.path.splitext(form.image_file.data.filename)
    new_img_filename = random_hex + file_extension
    img_path = os.path.join(app.root_path, "static/product_images", new_img_filename)
    img = Image.open(form.image_file.data)
    img.thumbnail((550, 500))
    img.save(img_path)
    new_product = Product(
      name=form.name.data,
      cost=form.cost.data,
      stock=form.stock.data,
      description=form.description.data,
      img_filename=new_img_filename
    )
    db.session.add(new_product)
    db.session.commit()
    flash("Product successfully added", "success")
    return redirect(url_for("admin_blueprint.admin_dashboard"))
  return render_template("admin_addproduct.html", title="Admin Add Product", form=form)


@admin_blueprint.route("/admin/product/<int:product_id>/update", methods=["GET", "POST"])
@login_required
def admin_updateproduct(product_id):
  product = Product.query.get_or_404(product_id)
  form = AdminUpdateProductForm()
  new_img_filename = None
  if form.validate_on_submit():
    product2 = Product.query.filter_by(name=form.name.data).first()
    if product2 and product2.name != product.name:
      flash("A product with the same name already exists", "danger")
      return redirect(url_for("admin_blueprint.admin_updateproduct", product_id=product.id))
    if form.image_file.data:
      current_img_path = os.path.join(app.root_path, "static/product_images", product.img_filename)
      if os.path.exists(current_img_path):
        os.remove(current_img_path)
      random_hex = secrets.token_hex(8)
      _, file_extension = os.path.splitext(form.image_file.data.filename)
      new_img_filename = random_hex + file_extension
      new_img_path = os.path.join(app.root_path, "static/product_images", new_img_filename)
      img = Image.open(form.image_file.data)
      img.thumbnail((550, 500))
      img.save(new_img_path)
    product.name = form.name.data
    product.cost = form.cost.data 
    product.stock = form.stock.data
    product.description = form.description.data
    if new_img_filename:
      product.img_filename = new_img_filename
    db.session.commit()
    flash("Product has been successfully updated", "success")
    return redirect(url_for("admin_blueprint.admin_dashboard"))
  form.name.data = product.name
  form.stock.data = product.stock
  form.cost.data = product.cost
  form.description.data = product.description
  return render_template('admin_updateproduct.html', title="Update Product", form=form, product=product)


@admin_blueprint.route("/admin/product/<int:product_id>/remove")
@login_required
def admin_removeproduct(product_id):
  product = Product.query.get_or_404(product_id)
  img_path = os.path.join(app.root_path, "static/product_images", product.img_filename)
  if os.path.exists(img_path):
    os.remove(img_path)
  db.session.delete(product)
  db.session.commit()
  flash("Product successfully removed", "danger")
  return redirect(url_for("admin_blueprint.admin_dashboard"))


@admin_blueprint.route("/admin/logout")
@login_required
def admin_logout():
  logout_user()
  flash('You have successfully logout', 'danger')
  return redirect(url_for('product_blueprint.allproducts'))

shop/routes/cart_routes.py
from flask import Blueprint, render_template, session, redirect, abort
from shop.utils import create_paymongo_checkout_session
from shop.forms import CheckoutForm

cart_blueprint = Blueprint("cart_blueprint", __name__)

@cart_blueprint.route("/cart", methods=["GET", "POST"])
def cart():
  form = CheckoutForm()
  if form.validate_on_submit():
    try:
      line_items = []
      for cart_item in session["cart"]:
        line_items.append({
          "amount": int(cart_item["cost"] * 100),
          "currency": "PHP",
          "name": cart_item["name"],
          "quantity": cart_item["quantity"]
        })

      paymongo_checkout_id, paymongo_checkout_url = create_paymongo_checkout_session(
        line1=form.line1.data,
        city=form.city.data,
        state=form.state.data,
        postal_code=form.postal_code.data,
        country=form.country.data,
        name=f"{form.firstname.data} {form.lastname.data}",
        email=form.email.data,
        phone=form.phone.data,
        line_items=line_items
      )

      session.pop("cart")
      return redirect(paymongo_checkout_url)
    except Exception as e:
      print(e)
      abort(500)
  
  return render_template("cart.html", title="Cart", form=form)

shop/routes/product_routes.py
from flask import Blueprint, render_template, session, redirect, url_for, abort, flash
from shop.models import Product
from shop.forms import AddToCartForm

product_blueprint = Blueprint("product_blueprint", __name__)

@product_blueprint.get("/")
def allproducts():
	products = Product.query.all()
	return render_template("home.html", title="Home", products=products)


@product_blueprint.get("/product/<int:product_id>")
def product(product_id):
  product = Product.query.get_or_404(product_id)
  form = AddToCartForm()
  return render_template("product.html", title=f"{product.name}", product=product, form=form)


"""
Helper funcntion that checks if cart_item which is a dictionary
is inside of session['cart'] 
"""
def isItemInCartSess(cart_session, cart_item):
  for i in cart_session:
    if i["id"] == cart_item["id"]:
      return True
  return False


@product_blueprint.post("/product/<int:product_id>/addtocart")
def addtocart(product_id):
  product = Product.query.get_or_404(product_id)
  form = AddToCartForm()
  if form.validate_on_submit():
    cart = []
    cart_item = {
      "id": product.id,
      "name": product.name,
      "cost": product.cost,
      "quantity": form.quantity.data
    }
    if "cart" not in session:
      session["cart"] = cart
      session["cart"].append(cart_item)
    elif "cart" in session:
      if isItemInCartSess(session["cart"], cart_item) == False:
        session["cart"].append(cart_item)
      elif isItemInCartSess(session["cart"],cart_item) == True:
        for i in session["cart"]:
          if i["id"] == cart_item["id"]:
            i["quantity"] += cart_item["quantity"]
    flash("Item successfully added to Cart", "success")
    return redirect(url_for("product_blueprint.product", product_id=product.id))
  else:
    abort(500)

@product_blueprint.get("/product/<int:product_id>/removefromcart")
def removefromcart(product_id):
  product = Product.query.get_or_404(product_id)
  cart = session["cart"]
  session.pop("cart")
  for cart_item in cart:
    if cart_item["id"] == product_id:
      cart.remove(cart_item)
  session["cart"] = cart
  return redirect(url_for("cart_blueprint.cart"))

shop/templates/admin_addproduct.html
{% extends "base.html" %}
{% block content %}
			<form action="{{url_for('admin_blueprint.admin_addproduct')}}" method="post" enctype="multipart/form-data">
				{{form.hidden_tag()}}

                <div class="field mb-5">
                    {{ form.image_file.label(class="is-size-4") }}
                    <div class="control">
                    	{{ form.image_file(class="is-size-6 p-1") }}
                    </div>
                    {% if form.image_file.errors %}
                    	{% for error in form.image_file.errors %}
                            <span class="has-text-danger">{{ error }}</span>
                        {% endfor %}
                    {% endif %} 
                </div>

            	<div class="field mb-5">
                	{{ form.name.label(class="is-size-4") }}
                	<div class="control">
                    	{{ form.name(class="is-size-6 p-1") }}
                	</div>
                	{% if form.name.errors %}
                		{% for error in form.name.errors %}
                    		<span class="has-text-danger">{{ error }}</span>
                		{% endfor %}
                	{% endif %} 
            	</div>

            	<div class="field mb-5">
                	{{ form.cost.label(class="is-size-4") }}
                	<div class="control">
                    	{{ form.cost(class="is-size-6 p-1") }}
                	</div>
                	{% if form.cost.errors %}
                    	{% for error in form.cost.errors %}
                        	<span class="has-text-danger">{{ error }}</span>
                    	{% endfor %}
                	{% endif %} 
            	</div>

            	<div class="field mb-5">
                	{{ form.stock.label(class="is-size-4") }}
                	<div class="control">
                		{{ form.stock(class="is-size-6 p-1") }}
                	</div>
                	{% if form.stock.errors %}
                    	{% for error in form.stock.errors %}
                        	<span class="has-text-danger">{{ error }}</span>
                    	{% endfor %}
                	{% endif %} 
            	</div>

                <div class="field mb-5">
                    {{ form.description.label(class="is-size-4") }}
                    <div class="control">
                        {{ form.description(class="my-textarea p-1") }}
                    </div>
                    {% if form.description.errors %}
                        {% for error in form.description.errors %}
                            <span class="has-text-danger">{{ error }}</span>
                        {% endfor %}
                    {% endif %} 
                </div>

				{{ form.submit(class="button is-info is-medium") }}
			</form>
{% endblock content %}

shop/templates/admin_dashboard.html
{% extends "base.html" %}
{% block content %}
			{% with messages = get_flashed_messages(with_categories=True) %}
			{% if messages %}
			<ul>
				{% for category, message in messages %}
				<li><strong class="has-text-{{category}}">{{message}}</strong></li>
				{% endfor %}
			</ul>
			{% endif %}
			{% endwith %}

			<h2 class="is-size-2 mb-4">Admin Dashboard</h2>

			<table class="table is-bordered">
				<thead>
					<tr>
						<th>Product Name</th>
						<th>Stock</th>
						<th>Cost</th>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					{% if products %}
						{% for product in products %}
							<tr>
								<td>{{product.name}}</td>
								<td>{{product.stock}}</td>
								<td>{{product.cost}}</td>
								<td><a href="{{url_for('admin_blueprint.admin_updateproduct', product_id=product.id)}}" class="button is-warning">Update</a></td>
								<td><a href="{{url_for('admin_blueprint.admin_removeproduct', product_id=product.id)}}" class="button is-danger">Remove</a></td>
							</tr>
						{% endfor %}
					{% endif %}
				</tbody>
			</table>
			<a href="{{url_for('admin_blueprint.admin_addproduct')}}" class="button is-info">Add Product</a>
{% endblock content %}

shop/templates/admin_login.html
{% extends "base.html" %}
{% block content %}
            <div class="has-text-centered">
                {% with messages = get_flashed_messages(with_categories=True) %}
                    {% if messages %}
                        <ul>
                        {% for category, message in messages %}
                            <li class="is-size-5 has-text-{{ category }}-dark has-text-weight-light">{{ message }}</li>
                        {% endfor %}
                        </ul>
                    {% endif %}
                {% endwith %}

                <h2 class="title is-size-1 mt-4 mb-6">Login</h2>

                <form method="POST" action="{{ url_for('admin_blueprint.admin_login') }}">
                    {{ form.hidden_tag() }}

                    <div class="field mb-5">
                        {{ form.name.label(class="is-size-4") }}
                        <div class="control">
                            {{ form.name(class="is-size-6 p-1") }}
                        </div>
                        {% if form.name.errors %}
                            {% for error in form.name.errors %}
                                <span class="has-text-danger">{{ error }}</span>
                            {% endfor %}
                        {% endif %} 
                    </div>

                    <div class="field">
                        {{ form.password.label(class="is-size-4") }}
                        <div class="control">
                            {{ form.password(class="is-size-6 p-1") }}
                        </div>
                        {% if form.password.errors %}
                            {% for error in form.password.errors %}
                                <span class="has-text-danger">{{ error }}</span>
                            {% endfor %}
                        {% endif %}
                    </div>

                    {{ form.submit(class="button is-success is-medium my-6") }}
                </form>

                {% if not admins %}
                    <p><strong>Haven't created an admin account yet? Click <a href="{{ url_for('admin_blueprint.admin_register') }}" class="has-text-blue">here</a></strong></p>
                {% endif %}
            </div>
{% endblock content %}

shop/templates/admin_register.html
{% extends "base.html" %}
{% block content %}
            <div class="has-text-centered">
                <h2 class="title is-size-1 mb-6">Create an Admin Account</h2>

                <form method="POST" action="{{ url_for('admin_blueprint.admin_register') }}">
                    {{ form.hidden_tag() }}
                
                    <div class="field mb-5">
                        {{ form.name.label(class="is-size-4") }}
                        <div class="control">
                            {{ form.name(class="is-size-6 p-1") }}
                        </div>
                        {% if form.name.errors %}
                            {% for error in form.name.errors %}
                                <span class="has-text-danger">{{ error }}</span>
                            {% endfor %}
                        {% endif %}
                    </div>
                
                    <div class="field mb-5">
                        {{ form.password.label(class="is-size-4") }}
                        <div class="control">
                            {{ form.password(class="is-size-6 p-1") }}
                        </div>
                        {% if form.password.errors %}
                            {% for error in form.password.errors %}
                                <span class="has-text-danger">{{ error }}</span>
                            {% endfor %}
                        {% endif %}
                    </div>

                    <div class="field">
                        {{ form.confirm_password.label(class="is-size-5") }}
                        <div classs="control">
                            {{ form.confirm_password(class="is-size-6 p-1") }}
                        </div>
                        {% if form.confirm_password.errors %}
                            {% for error in form.confirm_password.errors %}
                                <span class="has-text-danger">{{ error }}</span>
                            {% endfor %}
                        {% endif %}    
                    </div>

                    {{ form.submit(class="button is-success is-medium my-6") }}
                </form>
            </div>
{% endblock content %}

shop/templates/admin_updateproduct.html
{% extends "base.html" %}
{% block content %}
			{% with messages = get_flashed_messages(with_categories=True) %}
			{% if messages %}
			<ul class="mb-4">
				{% for category, message in messages %}
				<li><strong class="has-text-{{category}}">{{message}}</strong></li>
				{% endfor %}
			</ul>
			{% endif %}
			{% endwith %}

			<form action="{{url_for('admin_blueprint.admin_updateproduct', product_id=product.id)}}" method="post" enctype="multipart/form-data">
				{{form.hidden_tag()}}

                <div class="field mb-5">
                    {{ form.image_file.label(class="is-size-4") }}
                    <div class="control">
                        {{ form.image_file(class="is-size-6 p-1") }}
                    </div>
                    {% if form.image_file.errors %}
                        {% for error in form.image_file.errors %}
                            <span class="has-text-danger">{{ error }}</span>
                        {% endfor %}
                    {% endif %} 
                </div>

            	<div class="field mb-5">
                	{{ form.name.label(class="is-size-4") }}
                	<div class="control">
                    	{{ form.name(class="is-size-6 p-1") }}
                	</div>
                	{% if form.name.errors %}
                		{% for error in form.name.errors %}
                    		<span class="has-text-danger">{{ error }}</span>
                		{% endfor %}
                	{% endif %} 
            	</div>

            	<div class="field mb-5">
                	{{ form.cost.label(class="is-size-4") }}
                	<div class="control">
               	    	{{ form.cost(class="is-size-6 p-1") }}
                	</div>
                	{% if form.cost.errors %}
                    	{% for error in form.cost.errors %}
                        	<span class="has-text-danger">{{ error }}</span>
                    	{% endfor %}
                	{% endif %} 
            	</div>

            	<div class="field mb-5">
                	{{ form.stock.label(class="is-size-4") }}
                	<div class="control">
                		{{ form.stock(class="is-size-6 p-1") }}
                	</div>
                	{% if form.stock.errors %}
                    	{% for error in form.stock.errors %}
                        	<span class="has-text-danger">{{ error }}</span>
                    	{% endfor %}
                	{% endif %} 
            	</div>

                <div class="field mb-5">
                    {{ form.description.label(class="is-size-4") }}
                    <div class="control">
                        {{ form.description(class="my-textarea p-1") }}
                    </div>
                    {% if form.description.errors %}
                        {% for error in form.description.errors %}
                            <span class="has-text-danger">{{ error }}</span>
                        {% endfor %}
                    {% endif %} 
                </div>

				{{ form.submit(class="button is-warning is-medium") }}
			</form>
{% endblock content %}

shop/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% if title %}
        <title>Cozy Cart - {{title}}</title>
    {% else %}
        <title>Flask Shop</title>
    {% endif %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body class="has-background-light">
    <nav class="navbar has-shadow is-primary">
        <div class="navbar-brand ml-5">
            <a class="navbar-item title">Shop</a>
            <a id="navBarBurger" class="navbar-burger">
                <span></span>
                <span></span>
                <span></span>
            </a>
        </div>

        <div id="navBarMenu" class="navbar-menu pr-4">
            <div class="navbar-end">
                <a href="{{ url_for('product_blueprint.allproducts') }}" class="navbar-item is-size-5">Home</a>
                <a href="{{ url_for('cart_blueprint.cart') }}" class="navbar-item is-size-5">Cart</a>
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('admin_blueprint.admin_dashboard') }}" class="navbar-item is-size-5">Dashboard</a>
                    <a href="{{ url_for('admin_blueprint.admin_logout') }}" class="navbar-item is-size-5">Logout</a>
                {% endif %}
            </div>
        </div>
    </nav>

    <section class="section">
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </section>

    <script type="text/javascript" src="{{url_for('static', filename='script.js')}}"></script>
</body>
</html>

shop/templates/cart.html
{% extends "base.html" %}
{% block content %}
			{% if session["cart"] %}
			<div class="columns">
			<div class="column">
			<table class="table is-bordered">
				<thead>
					<tr>
						<th>Product Name</th>
						<th>Cost</th>
						<th>Quantity</th>
						<th></th>
					</tr>
				</thead>
				{% for cart_item in session["cart"] %}
				<tbody>
					<tr>
						<td>{{cart_item["name"]}}</td>
						<td>{{cart_item["cost"] * cart_item["quantity"]}}</td>
						<td>{{cart_item["quantity"]}}</td>
						<td><a href="{{url_for('product_blueprint.removefromcart', product_id=cart_item['id'])}}" class="button is-info">Remove from Cart</a></td>
					</tr>
				</tbody>
				{% endfor %}
			</table>
			</div>

			<div class="column has-text-centered">
    			<form action="{{url_for('cart_blueprint.cart')}}" method="post" class="columns">
					{{form.hidden_tag()}}

					<div class="column">
                		<div class="field mb-3">
                    		{{ form.firstname.label}}
                    		<div class="control">
                    			{{ form.firstname(class="is-size-6 p-1") }}
                    		</div>
                    		{% if form.firstname.errors %}
                    			{% for error in form.firstname.errors %}
                            		<span class="has-text-danger">{{ error }}</span>
                        		{% endfor %}
                    		{% endif %} 
                		</div>

            			<div class="field mb-3">
                			{{ form.lastname.label }}
                			<div class="control">
                    			{{ form.lastname(class="is-size-6 p-1") }}
                			</div>
                			{% if form.lastname.errors %}
                				{% for error in form.lastname.errors %}
                    				<span class="has-text-danger">{{ error }}</span>
                				{% endfor %}
                			{% endif %} 
            			</div>

            			<div class="field mb-3">
                			{{ form.email.label }}
                			<div class="control">
                    			{{ form.email(class="is-size-6 p-1") }}
                			</div>
                			{% if form.email.errors %}
                    			{% for error in form.email.errors %}
                        			<span class="has-text-danger">{{ error }}</span>
                    			{% endfor %}
                			{% endif %} 
            			</div>

            			<div class="field mb-3">
                			{{ form.phone.label }}
                			<div class="control">
                				{{ form.phone(class="is-size-6 p-1") }}
                			</div>
                			{% if form.phone.errors %}
                    			{% for error in form.phone.errors %}
                        			<span class="has-text-danger">{{ error }}</span>
                    			{% endfor %}
                			{% endif %} 
            			</div>
            		</div>

            		<div class="column">
                		<div class="field mb-3">
                    		{{ form.line1.label }}
                    		<div class="control">
                        		{{ form.line1(class="is-size-6 p-1") }}
                    		</div>
                    		{% if form.line1.errors %}
                       			{% for error in form.line1.errors %}
                            		<span class="has-text-danger">{{ error }}</span>
                        		{% endfor %}
                    		{% endif %} 
                		</div>

                		<div class="field mb-3">
                    		{{ form.city.label }}
                    		<div class="control">
                        		{{ form.city(class="is-size-6 p-1") }}
                    		</div>
                    		{% if form.city.errors %}
                       			{% for error in form.city.errors %}
                            		<span class="has-text-danger">{{ error }}</span>
                        		{% endfor %}
                    		{% endif %} 
                		</div>

                		<div class="field mb-3">
                    		{{ form.state.label }}
                    		<div class="control">
                        		{{ form.state(class="is-size-6 p-1") }}
                    		</div>
                    		{% if form.state.errors %}
                       			{% for error in form.state.errors %}
                            		<span class="has-text-danger">{{ error }}</span>
                        		{% endfor %}
                    		{% endif %} 
                		</div>

                		<div class="field mb-3">
                    		{{ form.country.label }}
                    		<div class="control">
                        		{{ form.country(class="is-size-6 p-1") }}
                    		</div>
                    		{% if form.country.errors %}
                       			{% for error in form.country.errors %}
                            		<span class="has-text-danger">{{ error }}</span>
                        		{% endfor %}
                    		{% endif %} 
                		</div>

                		<div class="field mb-3">
                    		{{ form.postal_code.label }}
                    		<div class="control">
                        		{{ form.postal_code(class="is-size-6 p-1") }}
                    		</div>
                    		{% if form.postal_code.errors %}
                       			{% for error in form.postal_code.errors %}
                            		<span class="has-text-danger">{{ error }}</span>
                        		{% endfor %}
                    		{% endif %} 
                		</div>

                		{{ form.submit(class="button is-danger mt-4") }}
                	</div>
				</form>
			</div>
			</div>

			{% else %}
			<div class="notification is-info">
				You don't have anything in the cart yet
			</div>

			{% endif %}
{% endblock content %}

shop/templates/home.html
{% extends "base.html" %}
{% block content %}
			{% with messages = get_flashed_messages(with_categories=True) %}
        	{% if messages %}
            	<ul>
                {% for category, message in messages %}
                	<li class="is-size-5 has-text-{{ category }}-dark has-text-weight-light">{{ message }}</li>
                {% endfor %}
            	</ul>
        	{% endif %}
        	{% endwith %}

        	{% if products %}
        	<div class="columns is-multiline my-3">
				{% for product in products %}
				<article class="column is-4 pr-4">
					<a href="{{url_for('product_blueprint.product', product_id=product.id)}}">
						<img src="{{url_for('static', filename='product_images/'+product.img_filename)}}" class="medium-img">
					</a>
					<p><strong class="is-size-6">{{product.name}}</strong></p>
					<p>{{product.cost}}</p>
				</article>
				{% endfor %}
			</div>

			{% else %}
			<div class="notification is-info">
				There are currently no available products
			</div>

			{% endif %}
{% endblock content %}

shop/templates/product.html
{% extends "base.html" %}
{% block content %}
			{% with messages = get_flashed_messages(with_categories=True) %}
				{% if messages %}
					<ul class="mb-4">
					{% for category, message in messages %}
						<li><strong class="has-text-{{category}}">{{message}}</strong></li>
					{% endfor %}
					</ul>
				{% endif %}
			{% endwith %}
			<div class="columns">
				<div class="column">
					<img src="{{url_for('static', filename='product_images/'+product.img_filename)}}" class="big-img">
				</div>
				<div class="column">
					<p class="title is-size-2 mt-6">{{product.name}}</p>
					<p class="subtitle is-size-4">Php{{product.cost}}</p>
					<p class="is-size-6 my-6">{{product.description}}</p>
					<p><strong class="has-text-success">{{product.stock}} left in stock</strong></p>
					<form action="{{url_for('product_blueprint.addtocart', product_id=product.id)}}" method="post">
		  				{{form.hidden_tag()}}
		  					
		  				<div class="field">
		  					<div class="control">
		  						{{form.quantity(class="is-size-5 p-1")}}
		  					</div>
		  					{% if form.quantity.errors %}
		  						{% for error in form.quantity.errors %}
		  							<span class="has-text-danger">{{error}}</span>
		  						{% endfor %}
		  					{% endif %}
		  				</div>

		  				{{form.submit(class="button is-danger is-medium")}}
					</form>
				</div>
			</div>
{% endblock content %}